---
title: Blogdown + Netlify
author: Misha Balyasin
date: '2017-07-23'
slug: blogdown-netlify
categories:
  - meta
tags:
  - R
---

I've been trying to get into blogging for quite some time, but laziness got the best of me every time. My first attempt amounted to fairly standard (at the time) use of Github Pages along with Jekyll based blog. You can still find it [here](http://romatik.github.io/). 

My personal gripe with it was the fact that in order to post anything you need to go through multiple manual steps. Granted, those steps can be automated, but each of those steps required non-trivial amount of work on my part to do it. But, remember, laziness...

So, my blog was dormant for 9 months until I've came across [this post](https://yihui.name/en/2017/06/netlify-instead-of-github-pages/) by Yihui Xie. He made it sound as if using his package [blogdown](https://bookdown.org/yihui/blogdown/) for back-end along with hosting it on [Netlify](https://www.netlify.com/) is as easy as apple pie.

Since my desire to have a blog didn't dissapear even after not blogging for 9 months, I've decided to give it a try. If you are reading this then you can see that he was right and blogging with `blogdown` and Netlify is actually easy. 

I won't go into details into how I've set this blog up because, to be honest, I've just followed `blogdown` book to the letter and I don't remember having any issues while doing so. But I do want to stress that with this combination creating and posting new blog-posts is actually easy since free (at the time of writing) continious integration from Netlify makes it really smooth. Pushing to Github is enough to trigger it and I don't need to think about anything else.

So, if you are thinking about blogging and writing about (or with) R then I can wholeheartedly recommend following Yihui's advice and give `blogdown` + Netlify a try.

The blog itself lives [here](https://github.com/romatik/netlify-blog).
