---
title: Democratization of tools
author: Misha Balyasin
date: '2017-07-30'
slug: democratization-of-tools
categories:
  - meta
tags: []
---

For a blog about R, I've been writing about actually doing R surprisingly little. But for some reason the topic of tools that make your life easier has been following me around ([The Baader-Meinhof Phenomenon](https://www.damninteresting.com/the-baader-meinhof-phenomenon/) in action most likely). 

So, while reading digest of [R-bloggers](http://r-bloggers.com) I've came across [this post](http://lbusettspatialr.blogspot.de/2017/07/the-new-modistsp-website-based-on.html) that talks about using `pkgdown` package to create a static web-site for the package ([this one](http://lbusett.github.io/MODIStsp/)). The package itself is not that interesting in this case, but what was interesting is this quote from the author:

> ... I was surprised at how simply the standard website could be tweaked to obtain a very nice (IMO) final result without needing any particular background on html, css, etc. !

It is interesting to me since it mirrors my [own experience](https://www.mishabalyasin.com/2017/07/23/blogdown-netlify/) pretty accurately. But on a more broader note the whole idea of creating tools (and that is not limited to R in any way) that democratize certain aspects of one's work/life is a topic that has been on my mind. 

In previous life I've been a researcher of higher education and it was the topic of MOOCs (massive open online courses) that converted me from someone who studied Applied Mathematics and Informatics in university to social sciences. In general, MOOCs have been geralded as a way to provide access to higher education to the most under-priviliged parts of world's society. So far that hasn't happened yet, but the progress is definitely there (at least from my point of view).

In any case, the whole point of writing this post was to put those thoughts down somewhere and strengthen neural connection in my brain about this idea so that next time I write something I'll think about how this function/tool/module can be used to improve someone else's life. 
